[tool.poetry]
name = "od_deaths"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.1.2"
pandas = "^1.4.2"
SQLAlchemy = "^1.4.37"

[tool.poetry.dev-dependencies]
pylint = "^2.14.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
